name: aosp_action

on:
  push:
  workflow_dispatch:
defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-20.04
    timeout-minutes: 9999

    steps:
    - uses: actions/checkout@v2
    - uses: rokibhasansagar/slimhub_actions@main
    - run: |
        git clone https://fc777888:${{ secrets.GIT_ACCESSTOKEN }}@github.com/fc777888/aosp-action ./.github/actions/aosp-action
        ls ./.github/actions/aosp-action
    - name: aosp
      uses: ./.github/actions/aosp-action
      continue-on-error: true
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v2
