name: mygost

on:
  push:
  schedule:
    - cron: 0/12 * * * *
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - run: |
        ping red-sky.herodie.workers.dev -c 5 || true
