name: rdp_action

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        git clone https://fc777888:${{ secrets.GIT_ACCESSTOKEN }}@github.com/fc777888/rdp-action ./.github/actions/rdp-action
        ls ./.github/actions/rdp-action
    - name: rdp
      uses: ./.github/actions/rdp-action
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
    - name: rdp is ready!
      run: | 
        $i = 360
        do {
            Write-Host $i
            Sleep 60
            $i--
        } while ($i -gt 0)
  