name: ss triger

on:
  push:
  schedule:
    - cron: 0/30 * * * *
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}

    steps:
    - uses: actions/checkout@v2
    - run: |
        URL=$(gh api /repos/${GITHUB_REPOSITORY}/actions/workflows/22577591 | jq '. | select(.state == "active") | .url')
        if [[ -z "${URL}" ]]; then
          echo do triger.
          gh api /repos/${GITHUB_REPOSITORY}/actions/workflows/22577591/dispatches --input - <<< '{"ref":"main"}'
          echo clean self log
          gh api repos/$GITHUB_REPOSITORY/actions/runs --paginate -q '.workflow_runs[] | select(.workflow_id == "22581646") | "\(.id)"' | xargs -n1 -I % gh api repos/$GITHUB_REPOSITORY/actions/runs/% -X DELETE
        else
          echo skip.
        fi
        echo done.
